spring:
  jpa:
    hibernate:
      ddl-auto: create
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
  profiles: client
server:
  port: 8002
book:
  service:
    name: book-service
    version: v1
user:
  service:
    name: user-service
    version: v1